spring.application.name=mangafy
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dev
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Security
jwt.secret=Qk5PTl9TRUNSRVRfQkFTRTY0X0tFWV9IRVJF

# Minio
storage.url=http://localhost:9000
storage.access-key=minioadmin
storage.secret-key=minioadmin
storage.bucket-name=mangafy