spring.application.name=${SPRING_APPLICATION_NAME:mangafy}
server.port=${SERVER_PORT:8080}

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:20MB}

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

# Security
jwt.secret=${JWT_SECRET:Qk5PTl9TRUNSRVRfQkFTRTY0X0tFWV9IRVJF}

# Minio / Storage
storage.url=${STORAGE_URL:http://localhost:9000}
storage.access-key=${STORAGE_ACCESS_KEY:minioadmin}
storage.secret-key=${STORAGE_SECRET_KEY:minioadmin}
storage.bucket-name=${STORAGE_BUCKET_NAME:mangafy}